server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

grpc:
  client:
    default:
      address: static://localhost:50051
      negotiationType: PLAINTEXT
    member-service:
      address: static://localhost:8081
      negotiationType: PLAINTEXT
    branch-service:
      address: static://localhost:8083
      negotiationType: PLAINTEXT
