app:
  server:
    type: GATEWAY_SERVICE
    id: gateway-service-1

server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

grpc:
  client:
    default:
      address: static://localhost:50051
      negotiationType: PLAINTEXT
    member-service:
      address: static://localhost:8081
      negotiationType: PLAINTEXT
    branch-service:
      address: static://localhost:8083
      negotiationType: PLAINTEXT

resilience4j:
  circuitbreaker:
    instances:
      member-service-circuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.ConnectException
          - java.lang.RuntimeException

jwt:
  secret-key: "rYfed5F12iViHmbB7ZufrxIR6MNLG67+4+b6+DhqcRJuFVe7/KxhIb4necxKaCDN"
