app:
  server:
    type: GATEWAY_SERVICE
    id: gateway-service-1

server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

grpc:
  client:
    default:
      address: static://localhost:50051
      negotiationType: PLAINTEXT
    member-service:
      address: static://localhost:8081
      negotiationType: PLAINTEXT
    branch-service:
      address: static://localhost:8083
      negotiationType: PLAINTEXT

jwt:
  secret-key: "rYfed5F12iViHmbB7ZufrxIR6MNLG67+4+b6+DhqcRJuFVe7/KxhIb4necxKaCDN"
